### ISSUE TITLE
Excessive memory usage with reasonably sized codebase

### ISSUE THREAD

**Issue by unode** [parsonsmatt/intero-neovim#100]
Gave the plugin a try while browsing through https://github.com/jgm/pandoc .
A couple of files and type inspections later I had one intero process eating over 10GB of RAM and sending all the system to swap.

This has potential to be a bug but just in case I'm asking too much of Intero/ghci, are there any recommendations on how to keep the memory usage under control?

**Comment by rdnetto** [comment]
Intero-neovim is just the Neovim plugin. For issues with the Intero executable itself, please raise them [here](https://github.com/commercialhaskell/intero).

FWIW, I've found it helpful to disable swap on systems I do Haskell development on, since I'd rather have the OOM killer reap a single process with a space leak than my entire session grind to a halt.
