### ISSUE TITLE
Neomake maker 

### ISSUE THREAD

**Issue by parsonsmatt** [parsonsmatt/intero-neovim#18]
Implement a maker for neomake. For reference, [this PR introduces ghc-mod and hlint](https://github.com/neomake/neomake/commit/9377fc40c5be3f2ef0c139d0924afe17f9e27461) makers for neomake:

``` vim
function! neomake#makers#haskell#ghcmod()
    " This filters out newlines, which is what neovim gives us instead of the
    " null bytes that ghc-mod sometimes spits out.
    let mapexpr = 'substitute(v:val, "\n", "", "g")'
    return {
        \ 'exe': 'ghc-mod',
        \ 'args': ['check'],
        \ 'mapexpr': mapexpr,
        \ 'errorformat':
            \ '%-G%\s%#,' .
            \ '%f:%l:%c:%trror: %m,' .
            \ '%f:%l:%c:%tarning: %m,'.
            \ '%f:%l:%c: %trror: %m,' .
            \ '%f:%l:%c: %tarning: %m,' .
            \ '%f:%l:%c:%m,' .
            \ '%E%f:%l:%c:,' .
            \ '%Z%m'
        \ }
endfunction

function! neomake#makers#haskell#hlint()
    return {
        \ 'errorformat':
            \ '%E%f:%l:%v: Error: %m,' .
            \ '%W%f:%l:%v: Warning: %m,' .
            \ '%C%m'
        \ }
endfunction
```

**Comment by lwm** [comment]
Hey, I was starting to look into this and have some free time. But I definitely need some help. The haskell maker setup runs things under `stack exec`, which is nice. However, this integration expects a command line interface right? Any idea what it would look like? 

```
\ 'exe': 'intero',
\ 'args': [???],
```

**Comment by rdnetto** [comment]
@lwm I looked at it the other day and it's quite non-trivial, precisely because Neomake wants to run an external command, and intero-neovim communicates with a background process via Vimscript.

I think the easiest way of implementing it would probably be to find a way to call into the running process from an external process, either directly or through Neovim. Adding this directly to Intero is probably the best way to enable re-use in other editors, but it's probably worth running this past the Intero maintainers first.

**Comment by lwm** [comment]
Completely out my depth here but anyway, forging on with https://github.com/commercialhaskell/intero/issues/390.

**Comment by rdnetto** [comment]
Since previous investigations seem to have stalled, and #44 makes it easier to implement new features, I might take another look at this.

Thinking out loud:
* what does Neomake give us? would it make sense to populate the quickfix list directly?
* Neomake has the following nice-to-haves:
    * provides an API for integration with airline and other prompts
    * avoids users needing to change their normal mapping for building a project to a Haskell-specific one
    * icons in the margins, underlining at the location of error

* the complexity of using Neomake comes from the desire to trigger the reload from Neomake, but that's not a hard requirement

Possible implementation: implement a maker that just cats a text file. Then whenever the project is reloaded, we can update the file and trigger the maker.

* users need to invoke `InteroReload` instead of `Neomake!`
* still get all the other benefits of Neomake
* hacky, but a lot simpler than the complex logic we'd need for Neomake to talk to the Intero process
* doesn't support incremental progress during compilation
     * neither does neomake though - see https://github.com/neomake/neomake/issues/112
     * a variation of this idea with a script that tails the file until it receives a signal to terminate would be pretty straightforward - could always implement it later

**Comment by lwm** [comment]
Holy moly, we're getting closer! Make it happen @rdnetto :+1:

**Comment by rdnetto** [comment]
Well, that was surprisingly straight-forward. :)

**Comment by lwm** [comment]
Just took it for a spin, works really well, thanks a million!

**Comment by craigdallimore** [comment]
Hi! Seems like I get a warning - `Neomake not detected. Flychecking will be disabled` - whenever I open a `.hs` file now. I'm not quite sure if I should have neomake installed from here on?

If I do, another plugin (`w0rp/ale`) [complains](https://github.com/w0rp/ale/blob/3a74d242f9b2b09dd066e5cfd6ed9a0149395b87/after/plugin/ale.vim#L31-L33) about its presence.

**Comment by craigdallimore** [comment]
I'm going to investigate `neomake` and see if I can use it alongside `ale` without warnings.

**Comment by jez** [comment]
@craigdallimore Intero now has a global option to never use `:Neomake` if you want to use `intero-neovim` alongside ALE:

```
let g:intero_use_neomake = 0
```

**Comment by craigdallimore** [comment]
Amazing, thank you @jez !
