### ISSUE TITLE
InteroType opens many splits

### ISSUE THREAD

**Issue by expipiplus1** [parsonsmatt/intero-neovim#21]
I've tried this with the head of intero-neovim and versions `006f9c0`, `18cbe74` and `634d59f` of neovim.

I have made a small change to `process.vim` to use `cabal repl --with-ghc intero` instead of `stack exec`.

To reproduce:

Open a haskell file
run `InteroType` with the cursor over name
Observe a new split being opened every 100ms :)

The splits all show an Intero session.

Can anyone else reproduce this, or is it something in my config?

**Comment by expipiplus1** [comment]
Commands such as `InteroTypeInsert` also open a split and don't keep it hidden.

**Comment by parsonsmatt** [comment]
Ah, yes -- [this is why](https://github.com/parsonsmatt/intero-neovim/blob/master/autoload/intero/util.vim#L8-L12):

```vimscript
function! intero#util#get_intero_window()
    " Returns the window ID that the Intero process is on, or -1 if it isn't
    " found.
    return bufwinnr('stack ghci --with-ghc intero')
endfunction
```

It keeps looking for the Intero window, failing to find it, and then opening up a new one because they're named differently.

A fix for this would be to refer to the same command used to start the process and lookup the buffer. Since I don't anticipate `cabal repl` support, I'm going to hold off on this.
