### ISSUE TITLE
RFC: Should InteroGoToDef push to the tag stack?

### ISSUE THREAD

**Issue by parsonsmatt** [parsonsmatt/intero-neovim#55]
Currently, go to definition works! But there's no esay way to jump back.

Possible fix: use the tags mechanism so `C-]` and `C-t` work.

**Comment by jez** [comment]
You can always use `CTRL-O` and `CTRL-I` which keep track of every jump point.

Mnemonics:
- `CTRL-O` "out" (jumps back out to where you were)
- `CTRL-I` "in" (jumps back in to where you just "out"'d from)

**Comment by parsonsmatt** [comment]
That works, neat!

To change course a bit: should `InteroGoToDef` push something onto the tags stack? That's how I'm used to navigating that sort of thing, and it was a bit surprising to me that it didn't work.

**Comment by jez** [comment]
Hm I'm not sure. I usually default to `CTRL-O`/`CTRL-I` because it works for tags and non tags (and I rarely think of the difference between the two, so having a separate tagstack doesn't benefit much).

That being said, from a quick skim of `:help tags`, it seems like *if* we wanted to, modifying the tag stack for `:InteroGoToDef` wouldn't be out of place. Up to you if you want to add it.

**Comment by parsonsmatt** [comment]
I'm going to close this; `C-o` and `C-i` are a perfectly fine tool for this.

If anyone wants this to operate on the tag stack, feel free to reopen.

**Comment by easoncxz** [comment]
I'm currently using `C-o` and it works fine when the definition is in another file. However, if the definition is in the same file as the usage, then `C-o` doesn't put my cursor to where the cursor previously was (i.e. at the place of usage). Coming from using, for example, `gd`, I wasn't expecting to lose my cursor position. Am I missing something, or is this just how things are at the moment?
