### ISSUE TITLE
Properly support Python 3

### ISSUE THREAD

**Issue by goetzc** [parsonsmatt/intero-neovim#75]
Pointing this out in the README.md would be handy, as there is also Python version 3 support for the nvim plugins. Plus the link https://github.com/neovim/python-client

**Comment by lwm** [comment]
Uhhh, I don't think that is a requirement? I use with py3 and in development as well.

**Comment by jez** [comment]
I think we should actually just drop the Python dependency at all. The only place we use it is to strip ANSI control characters from the string (i.e., in case there were color code sequences). Then we wouldn't have to worry about Python at all.

**Comment by rdnetto** [comment]
I think we definitely want to be explicit about whether we only support Python 2, or both 2 and 3. If the latter, we definitely want our CI running in both versions, because it's really easy to accidentally introduce code that only works in one version. (I learnt this the hard way in another Vim plugin)

@jez The reason we use Python for stripping the control chars is that it's a lot easier to express the regexes in Python, due to raw strings and hex literals. Given that the regexes are already quite complex, I think they'd be much harder to read/maintain in pure Vimscript.

@lwm What's the output of `:py import sys; print(sys.version)` for you? I'd have thought it would be Python 2, but I couldn't see anything specific in the docs.

**Comment by lwm** [comment]
> @lwm What's the output of :py import sys; print(sys.version) for you? I'd have thought it would be Python 2, but I couldn't see anything specific in the docs.

I use [pipenv](http://docs.pipenv.org) to manage my python hacking, and use `pipenv --three`, so it's always Python 3.5 or so.

**Comment by rdnetto** [comment]
So, according to [this](https://github.com/zchee/deoplete-jedi/wiki/Setting-up-Python-for-Neovim), it turns out that this is a significant difference between Vim and Neovim. In Vim, the version of Python was determined at compile-time (which meant that `:py` would resolve to Python 2), but in Neovim it's just determined by whatever version of Python happens to be in PATH.

Given that, I think we're going to have to support both versions, otherwise we're going to be broken for users running in a virtualenv or using Arch Linux (which has `python` symlinked to `python3` by default).

**Comment by lwm** [comment]
I'll take a stab at updating the Travis configuration!
