### ISSUE TITLE
Commands print excessive output

### ISSUE THREAD

**Issue by unode** [parsonsmatt/intero-neovim#80]
I have `:set prompt "\ESC[0;35mImports: \ESC[1;34m%s\n\ESC[1;32mλ> \ESC[m"` and while the default regex works, the `Imports:`line is always printed on every output, e.g. `:InteroType` produces: 
```
it :: FilePath -> IO Bool
Imports: *Main ...
```

The documentation isn't clear on what needs to be captured/ignored with the prompt regex.

Possibly related to #79.

**Comment by rdnetto** [comment]
The prompt regex should match everything from the start of the line to the end of the prompt, excluding ANSI escape codes (since we strip those before applying it). In your case, you want to include `Imports: ` in it.

Agreed that it's related to #79 - the regex is an implementation detail that users should not have configure, and won't once that's implemented.

**Comment by parsonsmatt** [comment]
I'm going to close this as it seems that @rdnetto has answered the question re current behavior. When #79 is fixed then this will be a non-issue
